# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.16.9

# Mod Properties
mod_version=1.0.1
maven_group=com.awa.kissmod
archives_base_name=kiss-mod
#2 in build.yml and 1 in kiss-mod.mixins.json
java_version=21