# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1

# Dependencies
fabric_version=0.144.3+26.1
#https://modrinth.com/mod/modmenu/versions
modmenu_version=18.0.0-alpha.8
#https://modrinth.com/mod/cloth-config/versions
cloth_config_version=26.1.154
#https://modrinth.com/mod/proxlib/versions
proxlib_version=0.2.4+26.1