modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="kiss_mod"
version="${version}"
displayName="Kiss Mod"
displayURL = "https://modrinth.com/plugin/kiss-mod"
logoFile="assets/kiss-mod/icon.png"
authors="chicken_awa, lceLantern"
description="Kiss!"

[[dependencies.kiss_mod]]
modId="neoforge"
type="required"
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.kiss_mod]]
modId="minecraft"
type="required"
versionRange="${minecraft_version}"
ordering="NONE"
side="BOTH"

[[mixins]]
config="kiss-mod.mixins.json"
